name: rover
description: A new Flutter App that controls LED, Servo, and Stepper Motor using HC-06.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bluetooth_serial: ^0.2.2

flutter:
  uses-material-design: true